// Nombres oficiales de los 255 archimonstruos de Dofus Touch en francés e inglés,
// obtenidos de dofus-touch.com por ID (mismo ID que usa la app). El español ya
// viene directo del backend / DEMO_POOL, así que aquí solo hace falta fr/en.
import type { Lang } from "./i18n";

export const ARCHMONSTER_NAMES: Record<string, { fr: string; en: string }> = {
  "2544": { fr: "Abrakine le Sombre", en: "Treekness the Dark" },
  "2389": { fr: "Abrakildas le Vénérable", en: "Treektamak the Loud" },
  "2388": { fr: "Abrakanette l'Encapsulé", en: "Treekonk the Stunned" },
  "2309": { fr: "Abrakroc l'édenté", en: "Treekniddioo the Needy" },
  "2386": { fr: "Abraklette le Fondant", en: "Treekalack the Sad" },
  "2385": { fr: "Abrakadnuzar", en: "Treeknidylus" },
  "2381": { fr: "Abrinos le Clair", en: "Treekstalbal the Psychic" },
  "2384": { fr: "Aboudbra le Porteur", en: "Abounteous the Generous" },
  "2498": { fr: "Grandilok le Clameur", en: "Gwabbit the Wunner" },
  "2391": { fr: "Ameur la Laide", en: "Amlullabeye the Dreamer" },
  "2311": { fr: "Arabord la Cruche", en: "Arachma the Greek" },
  "2393": { fr: "Araknay la Galopante", en: "Arachnekros the Aggressive" },
  "2310": { fr: "Arakule la Revancharde", en: "Arakula the Carpature" },
  "2276": { fr: "Ribibi le Cher", en: "Rib the Torn" },
  "2312": { fr: "Arachitik la Souffreteuse", en: "Arachnangel the Hopeful" },
  "2314": { fr: "Bandson le Tonitruant", en: "Bandinamit the Explosive" },
  "2313": { fr: "Bandapar l'Exclu", en: "Bandirty the Messy" },
  "2545": { fr: "Barebourd le Comte", en: "Barbrosskam the Chief" },
  "2417": { fr: "Barchwork le Multicolore", en: "Blorko the Colourful" },
  "2361": { fr: "Tourbiket le Virevoletant", en: "Mopfeet the Circular" },
  "2400": { fr: "Bi le Partageur", en: "Biblokajin the Bald" },
  "2401": { fr: "Bistou le Rieur", en: "Bibloponey the Entertainer" },
  "2396": { fr: "Bistou le Quêteur", en: "Billbiblop the Great" },
  "2399": { fr: "Bilvoezé le Bonimenteur", en: "Biblopopo the Organiser" },
  "2403": { fr: "Wagnagnah le Sanglant", en: "Wabbin the Wich" },
  "2402": { fr: "Tiwa'Missou le Gateux", en: "Tiwana the Tokin'" },
  "2404": { fr: "Blorie L'assourdissante", en: "Blopulent the Pretentious" },
  "2405": { fr: "Blordur l'Infect", en: "Blorchid the Gorgeous" },
  "2406": { fr: "Bloporte le Veule", en: "Blopium the Delirious" },
  "2407": { fr: "Blof l'Apathique", en: "Blopal the Precious" },
  "2549": { fr: "Boostif l'Affamé", en: "Mushdrill the Piercer" },
  "2429": { fr: "Koamag'oel le Défiguré", en: "Koelloggs the Creator" },
  "2416": { fr: "Bworkasse le Dégoutant", en: "Bworak the Bohemian" },
  "2418": { fr: "Bwormage le Respectueux", en: "Bworkoder the Mazter" },
  "2430": { fr: "Chevaustine le Reconstruit", en: "Karnyona the Rider" },
  "2420": { fr: "Cavordemal le Sorcier", en: "Pygknightlion the Lousy" },
  "2431": { fr: "Saltoavan la Gymnaste", en: "Summersalt the Gymnast" },
  "2327": { fr: "Craraboss le Féérique", en: "Krabaoly the Patient" },
  "2419": { fr: "Caboume l'Artilleur", en: "Ganon the Dwarf" },
  "2344": { fr: "Pioulette la Coquine", en: "Piwilde the Bossie" },
  "2432": { fr: "Farlon l'Enfant", en: "Pighatchoo the Electrical" },
  "2320": { fr: "Chafmarcel le Fêtard", en: "Chaferotix the Sixtininth" },
  "2319": { fr: "Chafemal le Bagarreur", en: "Chaferanho the Essential" },
  "2422": { fr: "Chafrit le Barbare", en: "Chaferuption the Volcanic" },
  "2421": { fr: "Chaffoin le Sournois", en: "Chafred the Fish" },
  "2322": { fr: "Chalan le Commerçant", en: "Chafermented the Drinker" },
  "2373": { fr: "Champoul l'Illuminé", en: "Romush the Montecchi" },
  "2423": { fr: "Chamitant le Dillettante", en: "Shamassel the Off" },
  "2553": { fr: "Chamilero le Malchanceux", en: "Nidsally the Mushtang" },
  "2426": { fr: "Chamdblé le Cultivé", en: "Spimushuaia the Traveller" },
  "2323": { fr: "Chamchie le Difficile", en: "Matmushmush the Flasher" },
  "2552": { fr: "Chamoute le Duveteux", en: "Edvushmunch the Screamer" },
  "2425": { fr: "Chamflay le Ballonné", en: "Speedmush the Racer" },
  "2424": { fr: "Champayt l'Odorant", en: "Spimushty the Smelly" },
  "2427": { fr: "Champayr le Disjoncté", en: "Spimushtache the Hairy" },
  "2321": { fr: "Chafalfer l'Optimiste", en: "Chafaldrag the Charming" },
  "2566": { fr: "Gastroth la Contagieuse", en: "Calipzoth the Icy" },
  "2325": { fr: "Chonstip la Passagère", en: "Pigoblet the Useful" },
  "2439": { fr: "Crolnareff l'Exilé", en: "Croccyx the Bummer" },
  "2433": { fr: "Codenlgaz le Problème", en: "Codemonic the Mean" },
  "2378": { fr: "Cromikay le Néophyte", en: "Snowhitisha the Pure" },
  "2440": { fr: "Crognan le Barbare", en: "Lupisnockio the Woodwolf" },
  "2555": { fr: "Corboyard l'Enigmatique", en: "Kojaklator the Lollipoper" },
  "2326": { fr: "Craquetuss le Piquant", en: "Crackrockisree the Tiger" },
  "2436": { fr: "Crakmitaine le Faucheur", en: "Jiminicrackler the Conscious" },
  "2561": { fr: "Crathdogue le Cruel", en: "Crackedral the Majestic" },
  "2438": { fr: "Cramikaz le Suicidaire", en: "Cracklerod the Old" },
  "2556": { fr: "Craquetou le Fissuré", en: "Crackrodilrock the Helltune" },
  "2559": { fr: "Cruskof le Rustre", en: "Crabaramis the One" },
  "2560": { fr: "Crusmeyer le Pervers", en: "Crabathos the For" },
  "2558": { fr: "Crustensyl le Pragmatique", en: "Craborthos the All" },
  "2557": { fr: "Crustterus l'Organique", en: "Crabartanian the Allforone" },
  "2437": { fr: "Corpat le Vampire", en: "Crowmanion the Primitive" },
  "2348": { fr: "Pissdane l'Insipide", en: "Dandel the Boy" },
  "2360": { fr: "Ecorfé la Vive", en: "Barkricrac the Unsteady" },
  "2562": { fr: "Diskord le Belliqueux", en: "Ezothbeitor the Neighbour" },
  "2442": { fr: "Doktopuss le Maléfique", en: "Dokterwho the Tardisporter" },
  "2578": { fr: "Don Kizoth l'Obstiné", en: "Don Quizothe the Stubborn" },
  "2408": { fr: "Boombata le Garde", en: "Boombora the Dangerous" },
  "2465": { fr: "Dragnoute l'Irascible", en: "Drakokidoki the Volunteer" },
  "2448": { fr: "Dragoo le Cramoisi", en: "Dreggooliz the Macho" },
  "2450": { fr: "Dragkouine la Magnifique", en: "Dreggump the Magnificent" },
  "2446": { fr: "Dragma le Bouillant", en: "Dreggooniz the Adventurous" },
  "2372": { fr: "Dragmoclaiss le Fataliste", en: "Dreggatón the Latino" },
  "2458": { fr: "Draquetteur le Voleur", en: "Draghouse the Cynical" },
  "2454": { fr: "Dragminster le Magicien", en: "Dragorse the Wild" },
  "2457": { fr: "Dragybuss le Sucré", en: "Dragospel the Black" },
  "2455": { fr: "Dragalgan l'Effervescent", en: "Dragostino the Tiny" },
  "2456": { fr: "Dragtarus le Bellâtre", en: "Draigovsky the SocalledSwan" },
  "2379": { fr: "Draglida la Disparue", en: "Dragotitis the Painful" },
  "2459": { fr: "Dragioli le Succulent", en: "Dragoskovit the Barefoot" },
  "2367": { fr: "Dragstore le Généraliste", en: "Drakween the Cross Dresser" },
  "2453": { fr: "Dragtopaile l'Excavateur", en: "Dragaustin the Power" },
  "2449": { fr: "Dragnostik le Sceptique", en: "Dreggommomm the Chewer" },
  "2451": { fr: "Dragsta le Détendu", en: "Dragoolash the Stewed" },
  "2445": { fr: "Dragoeth le Penseur", en: "Dreggoog the Downunder" },
  "2368": { fr: "Dragtula l'Ancien", en: "Dreggershween the Tinpanalley" },
  "2464": { fr: "Dragdikal le Décisif", en: "Dregguantico the Trainer" },
  "2462": { fr: "Drakolage le Tentateur", en: "Drakoamax the Mad" },
  "2447": { fr: "Dragtonien le Malvoyant", en: "Dreggrieg the Pianist" },
  "2377": { fr: "Dragstayr le Fonceur", en: "Dragamemnon the Deadtroyer" },
  "2452": { fr: "Dragobert le Monarque", en: "Dragory the Violent" },
  "2369": { fr: "Dragstik le Frustre", en: "Dreggonzola the Cheesy" },
  "2616": { fr: "Ouature la Mobile", en: "Ougineemo the Lost" },
  "2524": { fr: "Ouassébo l'Esthète", en: "Ouassup the Irritating" },
  "2575": { fr: "Ouashouash l'Exubérant", en: "Ouassingiam the Tyrant" },
  "2615": { fr: "Scaratyn l'huitre", en: "Scaraheath the Hanger" },
  "2280": { fr: "Scapé l'Epée", en: "Scaratheef the Pincher" },
  "2282": { fr: "Scarouarze l'Epopée", en: "Scarabreef the Short" },
  "2283": { fr: "Scaramel le Fondant", en: "Scaramel the Melty" },
  "2550": { fr: "Brouste l'Humiliant", en: "Floratio the Investigator" },
  "2281": { fr: "Scarfayss le Balafré", en: "Scarahazad the Storyteller" },
  "2563": { fr: "Fantoch le Pantin", en: "Arepotair the Bespectacled" },
  "2466": { fr: "Fanlabiz le Véloce", en: "Aperobics the Dynamic" },
  "2468": { fr: "Fantrask le Rêveur", en: "Ghostabrava the Tourist" },
  "2467": { fr: "Fandanleuil le Précis", en: "Polterghaisk the Stray Soul" },
  "2565": { fr: "Floanna la Blonde", en: "Floramodovar the Stoned" },
  "2272": { fr: "Pichakoté le Dégoutant", en: "Snappy the Fishfrier" },
  "2358": { fr: "Tour le Vice", en: "Hunflower the Sinful" },
  "2376": { fr: "Gelaviv le Glaçon", en: "Jellyposukshion the Slim" },
  "2487": { fr: "Gelanal le Huileux", en: "Jellvis the King" },
  "2371": { fr: "Geloliaine l'Aérien", en: "Jelleno the Chinny" },
  "2493": { fr: "Ginsenk le Stimulant", en: "Ginsync the Hyperactive" },
  "2494": { fr: "Gobstiniais le Têtu", en: "Goblimp the Bis Kit" },
  "2292": { fr: "Grokosto le Bosco", en: "Bignstrong the Quartermaster" },
  "2497": { fr: "Guerrite le Veilleur", en: "Chukoalak the Norris" },
  "2569": { fr: "Guerumoth le Collant", en: "Zigzoth the Indecisive" },
  "2328": { fr: "Forboyar l'Enigmatique", en: "Smitherz the Licker" },
  "2353": { fr: "Sangria le Fruité", en: "Boarnigen the Damasker" },
  "2279": { fr: "Sampi l'Eternel", en: "Boarealis the Bright" },
  "2316": { fr: "Boulgourvil le Lointain", en: "Gobballyhoo the Noisy" },
  "2315": { fr: "Boudalf le Blanc", en: "Gobbach the Contrapuntaler" },
  "2317": { fr: "Boufdégou le Refoulant", en: "Gobballad the Romantic" },
  "2428": { fr: "Crok le Beau", en: "Crokdylann the Rebel" },
  "2324": { fr: "Bouflet le Puéril", en: "Gobbalky the Stubborn" },
  "4461": { fr: "Kaenekfeu le volubile", en: "Kaenekfire the Voluble" },
  "2502": { fr: "Kannibal le Lecteur", en: "Kannimantha the Maneater" },
  "2506": { fr: "Kannisterik le Forcené", en: "Kannarrie the Reckless" },
  "2507": { fr: "Kapota la Fraise", en: "Kanniranda the Maniac" },
  "2503": { fr: "Kanasukr le Mielleux", en: "Kaniedoss the Giggling" },
  "2570": { fr: "Kaskapointhe la Couverte", en: "Snailmetalika the Garagician" },
  "2571": { fr: "Kido l'Âtre", en: "Kidodo the Extinct" },
  "2572": { fr: "Kilimanj'haro le Grimpeur", en: "Killua the Assassin" },
  "2508": { fr: "Kiroyal le Sirupeux", en: "Kirevampiro the Wrestler" },
  "2505": { fr: "Kannémik le Maigre", en: "Kannemik the Skinny" },
  "2509": { fr: "Koaskette la Chapelière", en: "Crackoalak the Blonde" },
  "2513": { fr: "Koamaembair le Coulant", en: "Jackoalak the Ripper" },
  "2516": { fr: "Koakofrui le Confit", en: "Koaly the Fiddler" },
  "2518": { fr: "Koarmit la Batracienne", en: "Snapoalak the Redhead" },
  "2515": { fr: "Koasossyal le Psychopathe", en: "Popoalak the Mousibrown" },
  "2514": { fr: "Koalaboi le Calorifère", en: "Koalsen the Similar" },
  "2519": { fr: "Koalvissie le Chauve", en: "Koaldman the Garish" },
  "2517": { fr: "Koalastrof la Naturelle", en: "Koaldmen the Grumpy" },
  "2573": { fr: "Koktèle le Secoué", en: "Misskokoko the Channel" },
  "2520": { fr: "Kolforthe l'Indécollable", en: "Koleraspootin the Anesthesialogist" },
  "2301": { fr: "Trukul le Lent", en: "Glukoko the Slow" },
  "2521": { fr: "Krapahut le Randonneur", en: "Khameleltux the Tolerant" },
  "2522": { fr: "Kwoanneur le Frimeur", en: "Kwoanium the Smart" },
  "2331": { fr: "Larvapstrè le Subjectif", en: "Larvalencia the Orange" },
  "2332": { fr: "Larchimaide la Poussée", en: "Larvadelaide the Ozie" },
  "2574": { fr: "Larvonika l'Instrument", en: "Larvalaska the Cold" },
  "2525": { fr: "Let le Rond", en: "Lert Macraken the Used Emo" },
  "2460": { fr: "Drageaufol la Joyeuse", en: "Dragossiper the Nag" },
  "2363": { fr: "Bouliver le Géant", en: "Mopidyk the Mire" },
  "2532": { fr: "Maître Amboat le Moqueur", en: "Lord Lacedhat the Vampiric" },
  "2359": { fr: "Maître Onom le Régulier", en: "Fung Ku the Master" },
  "2531": { fr: "Maître Koantik le Théoricien", en: "Koalakropolis the King of the Hill" },
  "2461": { fr: "Dragonienne l'Econome", en: "Dragangora the Softy" },
  "2528": { fr: "Mamakomou l'Âge", en: "Mamankalak the Bibliomaniac" },
  "2529": { fr: "Mandalo l'Aqueuse", en: "Salamaa the Henpeck" },
  "4465": { fr: "Marude l'ensablé", en: "Marude the Sandy" },
  "2336": { fr: "Mosketère le Dévoué", en: "Moskoitus the Interruptor" },
  "2484": { fr: "Fourapin le Chaud", en: "Ambushapens the Unlucky" },
  "2554": { fr: "Chiendanlémin l'Illusionniste", en: "Warazpacho the Cherrilla" },
  "2333": { fr: "Milipatte la Griffe", en: "Milivanilli the Mime" },
  "2337": { fr: "Muloufok l'Hilarant", en: "Booty the Beast" },
  "2335": { fr: "Minsinistre l'Elu", en: "Minoskittle the Coloured" },
  "2568": { fr: "Germinol l'Indigent", en: "Minoknok the Visitor" },
  "2533": { fr: "Minoskour le Sauveur", en: "Milikkybum the Informer" },
  "2534": { fr: "Momikonos la Bandelette", en: "Jackoalak the Moonwalker" },
  "2577": { fr: "Meuroup le Prêtre", en: "Moops the Bubbleboy" },
  "2580": { fr: "Mufguedin le Suprême", en: "Mufavabeenz the Cannibal" },
  "2538": { fr: "Nakuneuye le Borgne", en: "Hazwonball the Hickler" },
  "4463": { fr: "Nanashi le virtuose", en: "Nanashi the Virtuoso" },
  "2539": { fr: "Nelvin le Boulet", en: "Nebuchadnezzar the Conqueror" },
  "2579": { fr: "Nerdeubeu le Flagellant", en: "Supergwass the Free" },
  "2540": { fr: "Nipulnislip l'Exhibitionniste", en: "Niptuk the Plasticynic" },
  "2541": { fr: "NodKoku le Trahi", en: "Kokonan the Talker" },
  "2542": { fr: "Arapliké la Calligraphe", en: "Arachiro the Calligrapher" },
  "2543": { fr: "Arakazam la Psychique", en: "Arakazam the Psychic" },
  "4457": { fr: "Onistérique le déchainé", en: "Onisterical the Unleashed" },
  "2585": { fr: "Osuxion le Vampirique", en: "Osurcus the Tamer" },
  "2318": { fr: "Boudur le Raide", en: "Bakeraider the Tomb" },
  "2584": { fr: "Palmiflette le Convivial", en: "Naypalm the Herbivorous" },
  "2583": { fr: "Palmiche le Serein", en: "Palmoleaf the Greasy" },
  "2581": { fr: "Palmbytch la Bronzée", en: "Palmella the Hefty" },
  "2582": { fr: "Palmito le Menteur", en: "Palmpilot the Yuppie" },
  "2397": { fr: "Porfavor le Quémandeur", en: "Pigstol the Sexy" },
  "2271": { fr: "Pékeutar le Tireur", en: "Fisheralf the Stewart" },
  "2293": { fr: "Tiwalpé le Dévêtu", en: "Tiwaldo the Hidden" },
  "2294": { fr: "Tiwoflan le Lâche", en: "Tiwascal the Wapper" },
  "2343": { fr: "Pioufe la Maquillée", en: "Piwi the Ermine" },
  "2341": { fr: "Pioustone le Problème", en: "Piwiki the Witty" },
  "2342": { fr: "Pioulbrineur le Mercenaire", en: "Piwicker the Manly" },
  "2270": { fr: "Piradain le Pingre", en: "Piralhaka the Intimidator" },
  "2346": { fr: "Pichduitre le Totem", en: "Snapple the Wise" },
  "2340": { fr: "Pichtoire l'Erudit", en: "Snapp the Dragon" },
  "2339": { fr: "Picht le Brioché", en: "Snappster the Sued" },
  "2338": { fr: "Pichdourse le Puissant", en: "Snappu the Shopkeep" },
  "2383": { fr: "Poolopo la Traditionnelle", en: "Cheech the Pussycat" },
  "2349": { fr: "Preskapwal le Tendancieux", en: "Prestreet the Fighter" },
  "2486": { fr: "Garsim le Mort", en: "Gargoyla the Paranoiac" },
  "2273": { fr: "Ratlbol l'Aigri", en: "Rattle the Hummer" },
  "2334": { fr: "Ratatouille le Cuisinier", en: "Chef Ratatouille" },
  "2275": { fr: "Ratéhaifaim le Professeur", en: "Ratilla the Hun" },
  "2350": { fr: "Radoutable le Craint", en: "Ratatouille the Stirrer" },
  "2354": { fr: "Sourizoto le Collant", en: "Famouse the Little-Known" },
  "2351": { fr: "Rauligo le Sale", en: "Raul Modrid the Chulo" },
  "2614": { fr: "Roy le Merlin", en: "Roy the Rover" },
  "2352": { fr: "Roz la Magicienne", en: "Roseanne the Yanker" },
  "2277": { fr: "Rostensyl la Cuisinière", en: "Zorrose the Messican" },
  "4459": { fr: "Sakkado la transporteuse", en: "Sakkado the Carrier" },
  "2587": { fr: "Seripoth l'Ennemi", en: "Zouzoth the Cuddly" },
  "2355": { fr: "Tofuldebeu l'Explosif", en: "Tofudd the Hunter" },
  "2285": { fr: "Scorpitène l'Enflammé", en: "Scorbison the Lonely" },
  "2482": { fr: "Fossamoel le Juteux", en: "Koalarchitect the Balancing Force" },
  "2287": { fr: "Serpistule le Purulent", en: "Quetnin the Fictional" },
  "2600": { fr: "Champmé le Méchant", en: "Mushketeer the Loyal" },
  "2551": { fr: "Champolyon le Polyglotte", en: "Mushuliet the Catapulet" },
  "2567": { fr: "Faufoll la Joyeuse", en: "Ryukualak the Bored" },
  "2588": { fr: "Sparoket le Lanceur", en: "Sparodi the Python" },
  "2347": { fr: "Pioussokrim le Délétère", en: "Piwinston the Churlish" },
  "2345": { fr: "Pioukas la Plante", en: "Piwiliam the Brave" },
  "2289": { fr: "Susbewl l'Hypocrite", en: "Suzessman the Enthusiastic" },
  "2546": { fr: "Bitoven le Musicien", en: "Pikhoven the Deaf" },
  "2356": { fr: "Tofurapin le Pétri", en: "Tofull the Optimist" },
  "2357": { fr: "Tofumanchou l'Empereur", en: "Tofulsom the Jailer" },
  "2296": { fr: "Tortilleur le Coulé", en: "Turtrenalds the Tragic" },
  "2295": { fr: "Tortenssia la Fleurie", en: "Turtan'ernie the Streetwise" },
  "2297": { fr: "Tortorak le Cornu", en: "Turticorn the Horned" },
  "2298": { fr: "Torthur la Lutte", en: "Turture the Hooded" },
  "2601": { fr: "Tromplamor le Survivant", en: "Trumpaynor the Survivor" },
  "2300": { fr: "Trooyé l'Oxydé", en: "Trooligan the Bulldogg" },
  "2299": { fr: "Tronkoneuz la Tranchante", en: "Trunkbeard the Gentle" },
  "2382": { fr: "Toutouf le Velu", en: "Follikoko the Tufted" },
  "2547": { fr: "Toufou le Benêt", en: "Prikoko the Witless" },
  "2589": { fr: "Ougaould le Parasite", en: "Ougathard the Fortunate" },
  "2302": { fr: "Vampunor le Glacial", en: "Vamp the Impalest" },
  "2308": { fr: "Wokènrôl le Danseur", en: "Wowalker the Egyptian" },
  "2307": { fr: "Wara l'Amer", en: "Worka the Willful" },
  "2306": { fr: "Warkolad l'Etreinte", en: "Warko the Inky" },
  "2305": { fr: "Watdogue le Bien Nommé", en: "Wabbitor the Apt" },
  "2304": { fr: "Wabbitud le Constant", en: "McWhabbit the Diehard" },
  "2495": { fr: "Gloubibou le Gars", en: "Greetdoff the Gentleman" },
  "2286": { fr: "Bourdilleu le Social", en: "Buzzby the Social" },
  "4350": { fr: "Gargantua la Dévoreuse", en: "Gargantua the Devourer" },
  "4352": { fr: "Dardamel la Kidnappeuse", en: "Gargamarak the Kidnapper" },
};

export function translateArchmonsterName(id: number | string, nameEs: string, lang: Lang): string {
  if (lang === "es") return nameEs;
  const entry = ARCHMONSTER_NAMES[String(id)];
  if (!entry) return nameEs;
  return lang === "fr" ? entry.fr : entry.en;
}