/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PositionIdRouteImport } from './routes/position.$id'
import { Route as ApiAuthDiscordLogoutRouteImport } from './routes/api/auth/discord/logout'
import { Route as ApiAuthDiscordLoginRouteImport } from './routes/api/auth/discord/login'
import { Route as ApiAuthDiscordCallbackRouteImport } from './routes/api/auth/discord/callback'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionIdRoute = PositionIdRouteImport.update({
  id: '/position/$id',
  path: '/position/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordLogoutRoute = ApiAuthDiscordLogoutRouteImport.update({
  id: '/api/auth/discord/logout',
  path: '/api/auth/discord/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordLoginRoute = ApiAuthDiscordLoginRouteImport.update({
  id: '/api/auth/discord/login',
  path: '/api/auth/discord/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordCallbackRoute = ApiAuthDiscordCallbackRouteImport.update({
  id: '/api/auth/discord/callback',
  path: '/api/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/join': typeof JoinRoute
  '/position/$id': typeof PositionIdRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/login': typeof ApiAuthDiscordLoginRoute
  '/api/auth/discord/logout': typeof ApiAuthDiscordLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/join': typeof JoinRoute
  '/position/$id': typeof PositionIdRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/login': typeof ApiAuthDiscordLoginRoute
  '/api/auth/discord/logout': typeof ApiAuthDiscordLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/join': typeof JoinRoute
  '/position/$id': typeof PositionIdRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/login': typeof ApiAuthDiscordLoginRoute
  '/api/auth/discord/logout': typeof ApiAuthDiscordLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/join'
    | '/position/$id'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/login'
    | '/api/auth/discord/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/join'
    | '/position/$id'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/login'
    | '/api/auth/discord/logout'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/join'
    | '/position/$id'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/login'
    | '/api/auth/discord/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  JoinRoute: typeof JoinRoute
  PositionIdRoute: typeof PositionIdRoute
  ApiAuthDiscordCallbackRoute: typeof ApiAuthDiscordCallbackRoute
  ApiAuthDiscordLoginRoute: typeof ApiAuthDiscordLoginRoute
  ApiAuthDiscordLogoutRoute: typeof ApiAuthDiscordLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position/$id': {
      id: '/position/$id'
      path: '/position/$id'
      fullPath: '/position/$id'
      preLoaderRoute: typeof PositionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/logout': {
      id: '/api/auth/discord/logout'
      path: '/api/auth/discord/logout'
      fullPath: '/api/auth/discord/logout'
      preLoaderRoute: typeof ApiAuthDiscordLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/login': {
      id: '/api/auth/discord/login'
      path: '/api/auth/discord/login'
      fullPath: '/api/auth/discord/login'
      preLoaderRoute: typeof ApiAuthDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/callback': {
      id: '/api/auth/discord/callback'
      path: '/api/auth/discord/callback'
      fullPath: '/api/auth/discord/callback'
      preLoaderRoute: typeof ApiAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  JoinRoute: JoinRoute,
  PositionIdRoute: PositionIdRoute,
  ApiAuthDiscordCallbackRoute: ApiAuthDiscordCallbackRoute,
  ApiAuthDiscordLoginRoute: ApiAuthDiscordLoginRoute,
  ApiAuthDiscordLogoutRoute: ApiAuthDiscordLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
